---
- name: run cisco ios commands
  hosts: routers
  connection: network_cli
  gather_facts: true  

  tasks:
    - name: run show ip int br
      cisco.ios.ios_command:
        commands: show ip int br
      register: output
    
    - name: show output
      debug:
        msg: "Command output {{ output }}"
