---
- name: configure cisco ios device
  hosts: routers
  gather_facts: no 
  connection_type: network_cli

  tasks:
    - name: change hostname
      cisco.ios.ios_config:
        lines:
            - hostname: R-changed  