---
- hosts: routers
  tasks:
    - name: Gather all legacy facts
      cisco.ios.ios_facts:
        gather_subset: all 
        
            
    
    -  name: Show host name
       debug:
        msg: "Hostname here"