---
- name: gathering facts
  hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: ios facts
      ios_facts:
        gather_subset: all
      register: output

    - name: debug output
      debug:
        var: output