---
- name: ospf testing
  hosts: routers
  connection: network_cli
  gather_facts: true

  tasks:
    - name: Delete all OSPF config from interfaces
      cisco.ios.ios_ospf_interfaces:
        state: deleted
      register: output

    - name: show output
      debug:
        msg: "Command output {{ output }}"
    
    - name: Override provided OSPF Interfaces configuration
      cisco.ios.ios_ospf_interfaces:
      config:
        - name: GigabitEthernet0/1
          address_family:
            - afi: ipv4
              process:
                id: 55
                area_id: 105
              adjacency: true
              priority: 20
              transmit_delay: 30
      state: overridden